version: "3.8"

services:
    ######## APP ########
    orange-app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: local
        environment:
            - CONTAINER_ROLE=APP
        volumes:
            - ../:/var/www/app:cached
        ports:
            - "8117:8080"
            - "5117:5117"
